### ISSUE TITLE
Out of memory while backing up labels

### ISSUE THREAD

**Issue by GoogleCodeExporter** [AkarshSatija/gmail-backup-com#3]
```
Command line backup of a year worth of emails. Invoked via
gmail-backup.py backup backup-directory email password 20100101 20110101

Linux Fedora Core 11, python 2.6

Output:
...
Skip   100.0%: message already stored (18049 of 194790)
Starting backup of labels
Error: Error while doing backup of label 'notifications/bacula'
Ignoring this error message.
If you want, please report the following traceback to 
gmail-backup-com-users@googlegroups.com
Thanks! (gmb.py revision 15):
Traceback (most recent call last):
  File "/home/nsushkin/download/gmail-backup-com-read-only/gmb.py", line 1222, in labelAssignment
    for msg in self.msgsWithLabel(i, where):
  File "/home/nsushkin/download/gmail-backup-com-read-only/gmb.py", line 1214, in msgsWithLabel
    yield self.connection.fetchMessageId(num)
  File "/home/nsushkin/download/gmail-backup-com-read-only/gmb.py", line 691, in fetchMessageId
    typ, data = self._call(self.con.fetch, num, '(BODY.PEEK[HEADER.FIELDS (Message-ID)])')
  File "/home/nsushkin/download/gmail-backup-com-read-only/gmb.py", line 767, in _call
    raise e
MemoryError

0KB/s (total: 2.74MB)        
```

Original issue reported on code.google.com by `nsush...@sushkins.net` on 14 Mar 2011 at 6:41

**Comment by GoogleCodeExporter** [comment]
```
AJAY CHOUHAN 





```

Original comment by `ajaynk.chouhan@gmail.com` on 7 Jan 2015 at 10:23

**Comment by GoogleCodeExporter** [comment]
```
AJAY CHOUHAN 
```

Original comment by `ajaynk.chouhan@gmail.com` on 7 Jan 2015 at 10:24
