### ISSUE TITLE
Zip error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [AkarshSatija/gmail-backup-com#9]
```
Steps to reproduce the problem:
  1. Creating backup into zip file
  2. At 2150406192 bytes file size error message displayed:

Error: Error while saving e-mail
Ignoring this error message.
If you want, please report the following traceback to 
gmail-backup-com-users@googlegroups.com 
Thanks! (gmb.py revision 15):
Traceback (most recent call last):
File "gmb.pyo", line 1254, in backup
File "gmb.pyo", line 1148, in store
File "zipfile.pyo", line 1100, in writestr
File "zipfile.pyo", line 998, in _writecheck
LargeZipFile: Zipfile size would require ZIP64 extensions

Product/OS versions:
  Gmail Backup Rev 15 (2011-03-07)
  Windows 7 (32 bit)
```

Original issue reported on code.google.com by `sipr...@gmail.com` on 31 Mar 2012 at 6:36

**Comment by GoogleCodeExporter** [comment]
```
Same error here.  How do I get gmail-backup to use zip64 on a windows 7x64 
system?
```

Original comment by `dsch...@kansasaviation.com` on 17 Jan 2014 at 1:52
